name: Convert Recipe Image to HTML

on:
  push:
    paths:
      - 'recipe.jpg'  # You can upload new images with the same name to re-trigger this

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests

    - name: Convert recipe image to HTML
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        import base64, requests, os
        from openai import OpenAI

        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

        with open("recipe.jpg", "rb") as img:
            image_data = base64.b64encode(img.read()).decode('utf-8')

        response = client.chat.completions.create(
            model="gpt-4-vision-preview",
            messages=[
                {"role": "system", "content": "Extract the recipe from the image and format it as schema.org compatible HTML."},
                {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_data}"}}
                    ]
                }
            ],
            max_tokens=2000
        )

        html = response.choices[0].message.content
        with open("public/recipe.html", "w") as f:
            f.write(html)

    - name: Commit and push HTML output
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add public/recipe.html
        git commit -m "Add new recipe HTML"
        git push
